module.exports = [
  {
    id: 1,
    name: "FPT Information System",
    location:
      "Tầng 22 toà nhà Keangnam Landmark 72, E6 Phạm Hùng, Nam Từ Liêm, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 5000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/fpt-information-system-0568949376dcab14abfb13e3e271447f-6548a75395c0b.jpg",
    website: "https://www.fis.com.vn/",
    contact_mail: "contact@fpt.com",
  },
  {
    id: 2,
    name: "Ngân Hàng TMCP Việt Nam Thịnh Vượng (VPBank)",
    location: "89 Láng Hạ, Đống Đa, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 10000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/ngan-hang-tmcp-viet-nam-thinh-vuong-vpbank-63e1cb5539e62.jpg",
    website: "https://www.vpbank.com.vn/",
    contact_mail: "chamsockhachhang@vpbank.com.vn",
  },
  {
    id: 3,
    name: "Công Ty TNHH Bảo Hiểm Nhân Thọ AIA (Việt Nam)",
    location:
      "Tòa nhà Petronas lầu 8, 235 Nguyễn Văn Cừ, p.Nguyễn Cư Trinh, Quận 1, TP HCM",
    country: "VN",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-bao-hiem-nhan-tho-aia-viet-nam-5fcefe44252e7.jpg",
    website: "https://www.aia.com.vn/vi/index.html",
    contact_mail: "mytrinhho2000@gmail.com",
  },
  {
    id: 4,
    name: "Công ty TNHH Concentrix Service Vietnam",
    location:
      "Tầng 4, 6 và 7, QTSC Building 1, Lô 34, đường số 14, Công viên phần mềm Quang Trung, phường Tân Chánh Hiệp, Quận 12, Thành Phố Hồ Chí Minh, Việt Nam",
    country: "US",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-concentrix-service-vietnam-a963cac26074348bc95ce4bf90dc9fb1-6423dfbc43963.jpg",
    website: "https://www.concentrix.com/",
    contact_mail: "hr.anvu1122@gmail.com",
  },
  {
    id: 5,
    name: "Trung Tâm Anh Ngữ ILA",
    location:
      "The Crest Residence, số 15, đường Trần Bạch Đằng, phường Thủ Thiêm, thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    country: "VN",
    province_id: 79,
    employees: 500,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/trung-tam-anh-ngu-ila-57bfa5cf4cf23_rs.jpg",
    website: "https://www.ila.edu.vn/",
    contact_mail: "vacancies@ilavietnam.edu.vn",
  },
  {
    id: 6,
    name: "Tổ chức Giáo dục quốc tế Langmaster",
    location: "Tòa nhà 201 Cầu Giấy, Q.Cầu Giấy, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 400,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/95UMEz8Uvwsc56NdTRk47FFlBOBdPEmo_1689071248____d38d8958820f4415fa920481e68bbbee.jpg",
    website: "https://langmaster.edu.vn/",
    contact_mail: "info@binggo.edu.vn",
  },
  {
    id: 7,
    name: "Hệ thống Anh ngữ AMES",
    location:
      "Hà Nội, Nam Định, Thái Nguyên, Hải Phòng, Hạ Long, Nghệ An, Thanh Hóa, Huế, Đà Nẵng, Quy Nhơn, Cần Thơ,Quảng Ninh, Hà Nam, Hưng Yên",
    country: "VN",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/he-thong-anh-ngu-ames-5ce6414e090e0.jpg",
    website: "jobs.ames.edu.vn",
    contact_mail: "gopy@ames.edu.vn",
  },
  {
    id: 8,
    name: "FE CREDIT",
    location: "Tầng trệt, 144 Cộng Hòa, P12, Q.Tân Bình, TP HCM.",
    country: "VN",
    province_id: 79,
    employees: 10000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/4309b044c7147d553222bc769da5161d-6194b4d027185.jpg",
    website: "https://www.fecredit.com.vn/",
    contact_mail: "dichvukhachhang@fecredit.com.vn",
  },
  {
    id: 9,
    name: "Công ty cổ phần Hạ tầng Viễn thông CMC Telecom",
    location: "Tầng 11, Tòa nhà CMC, 11 đường Duy Tân, quận Cầu Giấy, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 500,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-ha-tang-vien-thong-cmc-telecom-5af4f4a61b6e4_rs.jpg",
    website: "https://cmctelecom.vn",
    contact_mail: "cloud.ibu@cmctelecom.vn",
  },
  {
    id: 10,
    name: "NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN KỸ THƯƠNG VIỆT NAM",
    location:
      "Số 6 Quang Trung, phường Trần Hưng Đạo, Quận Hoàn Kiếm, Thành phố Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 10000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/ngan-hang-thuong-mai-co-phan-ky-thuong-viet-nam-632bbf5a763f7.jpg",
    website: "https://techcombankjobs.com/",
    contact_mail: "call_center@techcombank.com.vn",
  },
  {
    id: 11,
    name: "Công ty Cổ phần viễn thông FPT",
    location: "Tầng 2, tòa nhà FPT, Phố Duy Tân, Cầu Giấy, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 5000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
    website: "https://fptjobs.com",
    contact_mail: "vietbh.fpt@gmail.com",
  },
  {
    id: 12,
    name: "CÔNG TY TNHH MEDIASTEP SOFTWARE VIỆT NAM",
    location: "60A Trường Sơn, P2, Tân Bình, Tp. Hồ Chí Minh",
    country: "VN",
    province_id: 79,
    employees: 499,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-mediastep-software-viet-nam-5e548733aa731.jpg",
    website: "https://mediastep.com/",
    contact_mail: "nguyen.tran.thao@mediastep.com",
  },
  {
    id: 13,
    name: "Công ty TNHH Khu Du Lịch Vịnh Thiên Đường (ALMA)",
    location:
      "Tầng 15, tòa nhà Capital Tower, 109 Trần Hưng Đạo, Hà Nội, Việt Nam - Tầng 29, Tòa nhà Lim, Số 9-11 Tôn Đức Thắng, Quận 1, TP.HCM",
    country: "VN",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-khu-du-lich-vinh-thien-duong-alma-591a6f04eae05_rs.jpg",
    website: "http://alma.vn/",
    contact_mail: "alma@gmail.com",
  },
  {
    id: 14,
    name: "CÔNG TY TNHH GIẢI PHÁP KINH DOANH THẾ HỆ MỚI VNNG",
    location: "Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 500,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-giai-phap-kinh-doanh-the-he-moi-vnng-640fe72f8540f.jpg",
    website: "http://www.facebook.com/VNNGbyVNPAY",
    contact_mail: "chaultb@vnpay.vn",
  },
  {
    id: 15,
    name: "Công ty Cổ phần Đầu tư và Phát triển du lịch Ravi",
    location: "Tầng 5 Atermis Tower, 3 Lê Trọng Tấn, Thanh Xuân, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 250,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-dau-tu-va-phat-trien-du-lich-ravi-63ecad7250fe9.jpg",
    website: "https://ravi.vn/",
    contact_mail: "res@ravi.vn",
  },
  {
    id: 16,
    name: "Ngân Hàng TMCP An Bình",
    location:
      "Tầng 1,2,3 Tòa nhà Geleximco, số 36 Hoàng Cầu, Phường Ô Chợ Dừa, Quận Đống Đa, Thành Phố Hà Nội, Việt Nam",
    country: "VN",
    province_id: 1,
    employees: 5000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/ngan-hang-tmcp-an-binh-61d408f161bd6.jpg",
    website: "https://www.abbank.vn/",
    contact_mail: "dichvukhachhang@abbank.vn",
  },
  {
    id: 17,
    name: "CÔNG TY CỔ PHẦN SMILEE VIỆT NAM",
    location:
      "Số 138 Trần Vỹ, Phường Mai Dịch, Quận Cầu Giấy, Thành phố Hà Nội, Việt Nam",
    country: "VN",
    province_id: 1,
    employees: 99,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/euZxwfgBI59pNYbvMJuZdKtrUjQ6mGGJ_1680946520____edac48ae2d867304dbbfd991932ac5c8.png",
    website:
      "https://www.topcv.vn/cong-ty/cong-ty-co-phan-smilee-viet-nam/135823.html",
    contact_mail: "customer.lover@smilee.vn",
  },
  {
    id: 18,
    name: "CÔNG TY TNHH TƯ VẤN & ĐÀO TẠO ĐẠI DƯƠNG",
    location: "Số 25 Đường số 23, Phường Linh Chiểu, Quận Thủ Đức",
    country: "VN",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/VcHGfKX477DToFxwKnJ9mW1v8YFhEhEk_1649920055____5107dabb0160776d57f4fdf975da7104.jpg",
    website: "http://tinhocdaiduong.vn/vn/",
    contact_mail: "daiduong.hr1@gmail.com",
  },
  {
    id: 19,
    name: "CÔNG TY TNHH ALIBABA.COM (VIỆT NAM)",
    location:
      "Saigon Centre Tower 2, 67 Le Loi Street, Ben Nghe Ward, District 1, Ho Chi Minh City, Vietnam",
    country: "CN",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-alibabacom-viet-nam-c0bb32ea63e7bd3382cc1bcf7928be6c-64cb7c2f0c2d7.jpg",
    website: "https://www.alibaba.com/",
    contact_mail: "alibaba@gmail.com",
  },
  {
    id: 20,
    name: "CÔNG TY CỔ PHẦN BẤT ĐỘNG SẢN G.EMPIRE",
    location:
      "Trụ sở chính: Tầng 3, Toà Handiresco Complex, 31 Lê Văn Lương, Hà Nội/ VP 2: Tầng 2, Toà 17T1 Hapulico Complex, 81 Vũ Trọng Phụng, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 99,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-bat-dong-san-gempire-62908fae1a002.jpg",
    website: "https://gempire.vn/",
    contact_mail: "info@gempire.vn",
  },
  {
    id: 21,
    name: "CÔNG TY CỔ PHẦN EDUVATOR",
    location:
      "Số nhà 65, phố Yên Lãng, Phường Trung Liệt, Quận Đống Đa, Thành phố Hà Nội, Việt Nam",
    country: "VN",
    province_id: 1,
    employees: 400,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-eduvator-64213c06f3c25.jpg",
    website: "https://zim.vn/",
    contact_mail: "zim@gmail.com",
  },
  {
    id: 22,
    name: "Công ty TNHH TOTO Việt Nam",
    location: "Lô F1 - KCN Thăng Long - Kim Chung - Đông Anh - Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 200,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-toto-viet-nam-5d9ab7dcbcb1f.jpg",
    website: "https://vn.toto.com/",
    contact_mail: "toto@gmail.com",
  },
  {
    id: 23,
    name: "CÔNG TY TNHH BÁNH KẸO TÂN THẾ KỶ",
    location:
      "548-550 nguyễn Trãi, Phường 8, Quận 5, Thành phố Hồ Chí Minh, Việt Nam",
    country: "VN",
    province_id: 79,
    employees: 99,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-banh-keo-tan-the-ky-630d94845a581.jpg",
    website:
      "https://www.topcv.vn/cong-ty/cong-ty-tnhh-banh-keo-tan-the-ky/117214.html",
    contact_mail: "tantheki@gmail.com",
  },
  {
    id: 24,
    name: "CÔNG TY CỔ PHẦN CÔNG NGHỆ KIOTVIET",
    location:
      "Tòa nhà Waseco, Khu C, Tầng 6 - Số 10, Phổ Quang, Phường 02, Quận Tân Bình, Thành phố Hồ Chí Minh",
    country: "VN",
    province_id: 79,
    employees: 499,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-cong-nghe-kiotviet-64211ae60fe0e.jpg",
    website: "https://www.kiotviet.vn/",
    contact_mail: "jobs@kiotviet.com",
  },
  {
    id: 25,
    name: "Công ty Cổ phần Tập đoàn TH",
    location: "Xóm Sơn Liên - Xã Nghĩa Sơn - huyện Nghĩa Đàn - tỉnh Nghệ An",
    country: "VN",
    province_id: 40,
    employees: 10000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/vvLBunkWTv4pwHAizzlb0NFg8fKT1DmZ_1675680776____6e0657f4e4e07108dffa7c94cb781dfa.jpg",
    website: "https://thgroupglobal.com/",
    contact_mail: "thgroupglobal@gmail.com",
  },
  {
    id: 26,
    name: "Công ty TNHH Lotte Việt Nam",
    location:
      "Tòa báo Tuổi trẻ, Lầu 4, 60A Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, HCM",
    country: "VN",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-lotte-viet-nam-63a15c6fdb99a.jpg",
    website: "https://lotte.com.vn/",
    contact_mail: "sales_hcm@lotte.com.vn",
  },
  {
    id: 27,
    name: "Công ty Cổ phần Giáo dục & Đào tạo IMAP Việt Nam",
    location:
      "14 Trần Kim Xuyến, Phường Yên Hoà, Quận Cầu Giấy, Thành phố Hà Nội, Việt Nam",
    country: "VN",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-co-phan-giao-duc-dao-tao-imap-viet-nam-5da97e1f22484.jpg",
    website: "https://imap.edu.vn",
    contact_mail: "phongtuyendung@imap.edu.vn",
  },
  {
    id: 28,
    name: "CÔNG TY TNHH BẢO HIỂM HANWHALIFE VIỆT NAM",
    location: "63 Phan Đăng Lưu, Hòa Cường Bắc, Hải Châu, Đà Nẵng",
    country: "KR",
    province_id: 48,
    employees: 499,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/53681e711f1aba09def2c2be6d5ed51a-6181f90ec0555.jpg",
    website: "https://www.hanwhalife.com.vn/vi",
    contact_mail: "customer.service@hanwhalife.com.vn",
  },
  {
    id: 29,
    name: "Ngân Hàng Bảo Việt",
    location: "16 Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/ngan-hang-bao-viet-5937b34d972ad_rs.jpg",
    website: "https://www.baovietbank.vn/",
    contact_mail: "callcenter@baovietbank.vn",
  },
  {
    id: 30,
    name: "Ngân Hàng Thương Mại Cổ Phần Quốc Tế Việt Nam",
    location:
      "Tầng 1, (Tầng trệt) và Tầng 2 Tòa nhà Sailing Tower, số 111A Pasteur, Phường Bến Nghé, Quận 1, Hồ Chí Minh",
    country: "VN",
    province_id: 79,
    employees: 10000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/beac8465d62ef14e651a81e546dd9986-5fe1a719810ff.jpg",
    website: "https://careers.vib.com.vn/careers",
    contact_mail: "dvkh247@vib.com.vn",
  },
  {
    id: 31,
    name: "Bệnh Viện Đa Khoa Quốc Tế Thu Cúc - Chi Nhánh Công Ty Cổ Phần Y Khoa & Thẩm Mỹ Thu Cúc",
    location: "Trụ sở chính: 444 Hoàng Hoa Thám, Tây Hồ, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/benh-vien-da-khoa-quoc-te-thu-cuc-chi-nhanh-cong-ty-co-phan-y-khoa-amp-tham-my-thu-cuc-793fe6bf448001cb13596b014cd7ecb5-650416fca81e5.jpg",
    website: "https://thucuchospital.com/",
    contact_mail: "contact@thucuchospital.vn",
  },
  {
    id: 32,
    name: "Tổ chức Giáo dục và Đào tạo Apollo Việt Nam",
    location: "Số 181 Phố Huế, Hai Bà Trưng, Hà Nội",
    country: "VN",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/to-chuc-giao-duc-va-dao-tao-apollo-viet-nam-5dd4bce9c2fa0.jpg",
    website: "http://apollo.edu.vn/",
    contact_mail: "talk2us@apollo.edu.vn",
  },
  {
    id: 33,
    name: "UNIQLO VIETNAM CO., LTD.",
    location:
      "Tầng 26, Tòa nhà Trụ Sở Điều Hành Và Trung Tâm Thương Mại Viettel, 285 Cách Mạng Tháng Tám, Phường 12, Quận 10, Thành phố Hồ Chí Minh, Việt Nam",
    country: "JP",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/6vJFmQJvgOOyaD53GYE86sgHxmlfHVAC_1695628300____5c565acefcad36149cfb1baf6ea0c512.png",
    website: "https://www.uniqlo.com/vn/vi/",
    contact_mail: "uniqlo@gmail.com",
  },
  {
    id: 34,
    name: "CÔNG TY TNHH ALI LOGISTICS VIỆT NAM",
    location: "168 TRUNG KINH_ CẦU GIẤY_ HÀ NỘI",
    country: "VN",
    province_id: 1,
    employees: 300,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-ali-logistics-viet-nam-574ffa0271be33492bc658bd38a8068c-66232e161f9ee.jpg",
    website: "https://orderthangloi.com/",
    contact_mail: "cskh.orderthangloi@gmail.com",
  },
  {
    id: 35,
    name: "CÔNG TY TNHH BẢO TÍN MINH CHÂU",
    location:
      "Số 29 Trần Nhân Tông, Phường Nguyễn Du, Quận Hai Bà Trưng, Thành phố Hà Nội, Việt Nam",
    country: "VN",
    province_id: 1,
    employees: 10000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/https://static.topcv.vn/company_logos/cong-ty-tnhh-bao-tin-minh-chau-509d9df8c3bcab4171712bfacdf4b8cd-65a4fa0a9772f.jpg",
    website: "https://btmc.vn/",
    contact_mail: "cskh@btmc.vn",
  },
];
