module.exports = [
  {
    id: 1,
    name: "Công ty cổ phần chứng khoán VPS",
    industry: "Kinh doanh/ Bán hàng",
    location: "2A Đại Cồ Việt, Hai Bà Trưng, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 1200,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-chung-khoan-vps-5ff1a3dc0a075.jpg",
    website: "https://www.vps.com.vn/",
    contact_mail: "ckvps@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 2,
    name: "CÔNG TY TNHH CÔNG NGHỆ CAO VIỆT TRUNG",
    industry: "Kinh doanh/ Bán hàng",
    location:
      "Số B19 - 17 Khu B, KĐT mới Geleximco, Lê Trọng Tấn, Dương Nội, Hà Đông, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 100,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/FhCJykjpy7sv8hYzJe00msXdgHx6J6G5_1653355299____c8601340891bf0b1aa34bdccaaee0375.jpg",
    website: "https://www.cambienviet.vn/",
    contact_mail: "viettrung@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 3,
    name: "FPT Information System",
    industry: "Công nghệ thông tin",
    location:
      "Tầng 22 toà nhà Keangnam Landmark 72, E6 Phạm Hùng, Nam Từ Liêm, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 5300,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/fpt-information-system-5c7cac4be5cf1_rs.jpg",
    website: "https://www.fis.com.vn/",
    contact_mail: "contact@fpt.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 4,
    name: "Công ty Cổ phần Công nghệ Sen Đỏ",
    industry: "Kinh doanh/ Bán hàng",
    location: "Tầng 9, Tòa nhà Oriental, 324 Tây Sơn, Đống Đa, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-cong-nghe-sen-do-6357a4207d231.jpg",
    website: "https://www.sendo.vn/",
    contact_mail: "sendo@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 5,
    name: "CÔNG TY CỔ PHẦN ĐẦU TƯ & THƯƠNG MẠI QUỐC TẾ TÂM VIỆT",
    industry: "Kinh doanh/ Bán hàng",
    location: "ngõ 22 Đường Mạc Thái Tổ, Yên Hòa, Cầu Giấy, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/MgFfmZDcHYEo4D7CIs4fgL7ezBIfssjh_1658741919____af826fe24fde3512784e8a9f1f85c057.jpg",
    website: "https://duoctamviet.com.vn/",
    contact_mail: "tamviet@gmail.com",
    start_week_day: 2,
    end_week_day: 5,
  },
  {
    id: 6,
    name: "CÔNG TY TNHH ALI LOGISTICS VIỆT NAM",
    industry: "Kinh doanh/Bán hàng",
    location: "168 TRUNG KINH,CẦU GIẤY, HÀ NỘI",
    country: "Việt Nam",
    province_id: 1,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-ali-logistics-viet-nam-62a7f0b79767d.jpg",
    website: "https://orderthangloi.com/",
    contact_mail: "thangloi@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 7,
    name: "Công ty Cổ phần Giáo dục & Đào tạo IMAP Việt Nam",
    industry: "Hành chính/Văn phòng",
    location: "14 Trần Kim Xuyến, Yên Hoà,  Cầu Giấy, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 100,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-giao-duc-dao-tao-imap-viet-nam-5da97e1f22484.jpg",
    website: "https://imap.edu.vn/",
    contact_mail: "imapedu@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 8,
    name: "Công Ty TNHH Thiết Bị Khoa Học Việt Anh",
    industry: "Kinh doanh/Bán hàng",
    location: "Số 2 Lô 3A Khu đô thị Trung Yên, Trung Hoà, Cầu Giấy, Hà Nội",
    country: "Việt Nam",
    province_id: 1,
    employees: 100,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-thiet-bi-khoa-hoc-viet-anh-5f7d41fd236f9.jpg",
    website: "https://vietanhco.com.vn/",
    contact_mail: "vietanh@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 9,
    name: "CÔNG TY TNHH DCORP TOÀN CẦU",
    industry: "Kinh doanh/Bán hàng",
    location:
      "Căn hộ số 00.22, tầng trệt, Số 19 đường Tố Hữu, Phường Thủ Thiêm, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
    country: "Việt Nam",
    province_id: 79,
    employees: 100,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-dcorp-toan-cau-602dcf7ca2899.jpg",
    website: "https://kodo.vn/",
    contact_mail: "kodo@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 10,
    name: "CÔNG TY TNHH BẢO HIỂM NHÂN THỌ PRUDENTIAL VIỆT NAM",
    industry: "Bảo hiểm",
    location: "Toà nhà Prudential Tầng 05, 02-04 Bến Cần Giuộc, Quận 8, TPHCM",
    country: "Việt Nam",
    province_id: 79,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-bao-hiem-nhan-tho-prudential-viet-nam-kenh-kinh-doanh-qua-dien-thoai-5fabb2b39d30f.jpg",
    website: "https://www.prudential.com.vn/vi/",
    contact_mail: "prudential@gmai.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 11,
    name: "Công Ty Cổ Phần Đất Xanh Miền Trung",
    industry: "Kinh doanh/Bán hàng",
    location:
      "52-54 Võ Văn Kiệt, Phường An Hải Đông, Quận Sơn Trà, Thành Phố Đà Nẵng",
    country: "Việt Nam",
    province_id: 48,
    employees: 800,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-dat-xanh-mien-trung-62f31d414ed86.jpg",
    website: "https://datxanhmientrung.com/",
    contact_mail: "datxanh@gmail.com",
    start_week_day: 2,
    end_week_day: 5,
  },
  {
    id: 12,
    name: "Công Ty Cổ Phần Truyền Thông Kim Cương",
    industry: "Kinh doanh/Bán hàng",
    location: "215 Phan Đăng Lưu, Khuê Trung, Cẩm Lệ, Đà Nẵng",
    country: "Việt Nam",
    province_id: 48,
    employees: 500,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-truyen-thong-kim-cuong-6110e386df0ef.jpg",
    website: "https://callcenter.vn/",
    contact_mail: "kimcuong@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 13,
    name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI VÀ DỊCH VỤ KHO VẬN PHÚ HƯNG",
    industry: "Kinh doanh/Bán hàng",
    location:
      "Số 49 Đinh Tiên Hoàng, Phường Hoàng Văn Thụ, Quận Hồng Bàng, Thành phố Hải Phòng",
    country: "Việt Nam",
    province_id: 31,
    employees: 1000,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-thuong-mai-va-dich-vu-kho-van-phu-hung-636e09cfbd5f8.jpg",
    website: "http://phuhungjsc-eco.com/",
    contact_mail: "phuhung@gmail.com",
    start_week_day: 2,
    end_week_day: 6,
  },
  {
    id: 14,
    name: "Công ty cổ phần thời trang Xinh Xinh",
    industry: "Kinh doanh/Bán hàng",
    location: "11 Phạm Minh Đức , Máy Tơ , Ngô Quyền , Hải Phòng",
    country: "Việt Nam",
    province_id: 31,
    employees: 25,
    logo: "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/L634VwkVXfBUjOVGmYpTD2BSqPbUksm7_1664254283____0f63ac9d31189fb9cfa4708e4d2ec2ab.jpg",
    website: "https://thoitrangxinh.net/",
    contact_mail: "xinhxinh@gmail.com",
    start_week_day: 2,
    end_week_day: 5,
  },
];
